#basic structure of ansible playbook file 
- name: Install curl
  hosts: local
  become: true
  gather_facts: no  # Disable fact gathering
  tasks:
    - name: Ensure curl is installed
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: yes
